---
title: "Description of osi_phosphor"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document explains how the phosphorus indicator is calculated for each country and provides references


## Netherlands:



## Belgium (Flanders): 

## France:

Principle: The P-olsen is evaluated based on (1) the crop needs (high need, moderate need, low need) which is mentioned in the osi_crops table (2) the region (3) the soil type 

Two thresholds exist     (1) Timp = soil supplies the crop need, above this concentration no fertilizer response
                         (2) Trenf = below this threshold, soil needs to be replenished, fertilizer recommendation > supply 

The logistic function is based on the P Olsen evaluation in comparison with the export by the plant: score 0 when supply = 0; score 1 when supply = export. See page 33 for the crop-dependent interpretation of threshold values.
The growth rate and offset are based on the threshold values, the growth rate near the maximum is set to 1. 

See page 25 in reference. !!! Threshold values are given in mg/kg P2O5, conversion is done by =(Treshold/(141.943x10^3))x2x30.97*10^3

Threshold values do not differ much between regions and soil types, except  for craie and cranettes ('krijt' or 'chalk') which have pH above 8 (https://grandest.chambre-agriculture.fr/productions-agricoles/references-agronomiques/projet-auton/lazote-en-terres-de-craie/) and for 'aubues' which are calcareous soils (hence high pH)

Threshold values (in P2O5): 55-85, 55-85, 25-75 except for craie/cranettes/aubues: 145-210, 130-150, 60-135

Reference: Comifer, 2019, La fertilisation P-K-Mg; Les bases due raisonnement